-- Generated from lib/data/menu_seed.dart (confirmed project data only).
insert into public.categories (id, name_ar, name_en, is_visible, sort_order) values
  ('rizo', 'الريزو', '', true, 0),
  ('chicken', 'الدجاج', '', true, 1),
  ('pizza', 'البيتزا', '', true, 2),
  ('appetizers', 'المقبلات', '', true, 3),
  ('drinks', 'المشروبات', '', true, 4),
  ('burger', 'البركر', '', true, 5),
  ('sandwiches', 'السندويشات', '', true, 6),
  ('meals', 'الوجبات', '', true, 7),
  ('shawarma', 'الشاورما', '', true, 8),
  ('funker', 'الفنكر', '', true, 9)
on conflict (id) do nothing;

insert into public.products (id, category_id, name_ar, price, is_available, is_visible, sort_order, variants) values
  ('rizo-dari', 'rizo', 'ريزو كرسبي داري', 5000, true, true, 0, '[]'::jsonb),
  ('rizo-smoked', 'rizo', 'ريزو كرسبي مدخن', 5000, true, true, 0, '[]'::jsonb),
  ('rizo-chicken-shawarma', 'rizo', 'ريزو شاورما دجاج', 5000, true, true, 0, '[]'::jsonb),
  ('rizo-meat-shawarma', 'rizo', 'ريزو شاورما لحم', 6000, true, true, 0, '[]'::jsonb),
  ('chicken-full-rice', 'chicken', 'دجاجة مع تمن', 16000, true, true, 0, '[]'::jsonb),
  ('chicken-full-no-rice', 'chicken', 'دجاجة بدون تمن', 14000, true, true, 0, '[]'::jsonb),
  ('chicken-half-rice', 'chicken', 'نصف دجاجة مع تمن', 10000, true, true, 0, '[]'::jsonb),
  ('chicken-half-no-rice', 'chicken', 'نصف دجاجة بدون تمن', 8000, true, true, 0, '[]'::jsonb),
  ('wings-full-rice', 'chicken', 'نفر أجنحة دجاج مع تمن', 16000, true, true, 0, '[]'::jsonb),
  ('wings-full-no-rice', 'chicken', 'نفر أجنحة بدون تمن', 10000, true, true, 0, '[]'::jsonb),
  ('wings-half-rice', 'chicken', 'نصف نفر أجنحة مع تمن', 9000, true, true, 0, '[]'::jsonb),
  ('wings-half-no-rice', 'chicken', 'نصف نفر أجنحة بدون تمن', 7000, true, true, 0, '[]'::jsonb),
  ('pizza-chicken', 'pizza', 'بيتزا دجاج', 5000, true, true, 0, '[{"nameAr": "صغير", "price": 5000}, {"nameAr": "وسط", "price": 8000}, {"nameAr": "كبير", "price": 11000}]'::jsonb),
  ('pizza-meat', 'pizza', 'بيتزا لحم', 6000, true, true, 0, '[{"nameAr": "صغير", "price": 6000}, {"nameAr": "وسط", "price": 10000}, {"nameAr": "كبير", "price": 13000}]'::jsonb),
  ('pizza-pepperoni', 'pizza', 'بيتزا بيبروني', 5000, true, true, 0, '[{"nameAr": "صغير", "price": 5000}, {"nameAr": "وسط", "price": 8000}, {"nameAr": "كبير", "price": 11000}]'::jsonb),
  ('pizza-mixed', 'pizza', 'بيتزا مشكل', 6000, true, true, 0, '[{"nameAr": "صغير", "price": 6000}, {"nameAr": "وسط", "price": 10000}, {"nameAr": "كبير", "price": 13000}]'::jsonb),
  ('pizza-margherita', 'pizza', 'بيتزا مارغريتا', 5000, true, true, 0, '[{"nameAr": "صغير", "price": 5000}, {"nameAr": "وسط", "price": 7000}, {"nameAr": "كبير", "price": 10000}]'::jsonb),
  ('pizza-vegetable', 'pizza', 'بيتزا خضار', 4000, true, true, 0, '[{"nameAr": "صغير", "price": 4000}, {"nameAr": "وسط", "price": 7000}, {"nameAr": "كبير", "price": 10000}]'::jsonb),
  ('pizza-four-seasons', 'pizza', 'بيتزا فصول الأربعة', 6000, true, true, 0, '[{"nameAr": "صغير", "price": 6000}, {"nameAr": "وسط", "price": 10000}, {"nameAr": "كبير", "price": 13000}]'::jsonb),
  ('app-large', 'appetizers', 'مقبلات كبير', 5000, true, true, 0, '[]'::jsonb),
  ('app-medium', 'appetizers', 'مقبلات وسط', 3500, true, true, 0, '[]'::jsonb),
  ('app-small', 'appetizers', 'مقبلات صغير', 2500, true, true, 0, '[]'::jsonb),
  ('hummus', 'appetizers', 'حمص بطحينة', 2000, true, true, 0, '[]'::jsonb),
  ('tabbouleh', 'appetizers', 'تبولة', 2500, true, true, 0, '[]'::jsonb),
  ('eggplant', 'appetizers', 'باذنجانية', 2000, true, true, 0, '[]'::jsonb),
  ('sausage', 'appetizers', 'نقانق', 2000, true, true, 0, '[]'::jsonb),
  ('jajik', 'appetizers', 'جاجيك', 2000, true, true, 0, '[]'::jsonb),
  ('coleslaw', 'appetizers', 'كولسلو', 2500, true, true, 0, '[]'::jsonb),
  ('pepsi', 'drinks', 'بيبسي', 500, true, true, 0, '[]'::jsonb),
  ('dew', 'drinks', 'ديو', 500, true, true, 0, '[]'::jsonb),
  ('mirinda-orange', 'drinks', 'ميرندا برتقال', 500, true, true, 0, '[]'::jsonb),
  ('mirinda-apple', 'drinks', 'ميرندا تفاح', 500, true, true, 0, '[]'::jsonb),
  ('seven-up', 'drinks', 'سفن', 500, true, true, 0, '[]'::jsonb),
  ('burger-classic', 'burger', 'بركر كلاسيك', 4500, true, true, 0, '[]'::jsonb),
  ('burger-bbq', 'burger', 'بركر باربكيو', 4500, true, true, 0, '[]'::jsonb),
  ('burger-smoked', 'burger', 'بركر مدخن', 4500, true, true, 0, '[]'::jsonb),
  ('burger-dari', 'burger', 'بركر داري', 4500, true, true, 0, '[]'::jsonb),
  ('burger-chicken', 'burger', 'بركر دجاج', 4000, true, true, 0, '[]'::jsonb),
  ('burger-chicken-jumbo', 'burger', 'بركر دجاج جامبو', 6000, true, true, 0, '[]'::jsonb),
  ('burger-meat-jumbo', 'burger', 'بركر لحم جامبو', 7000, true, true, 0, '[]'::jsonb),
  ('sandwich-zinger', 'sandwiches', 'سندويش زنجر', 4000, true, true, 0, '[]'::jsonb),
  ('sandwich-fajita', 'sandwiches', 'سندويش فاهيتا', 4000, true, true, 0, '[]'::jsonb),
  ('sandwich-hawi', 'sandwiches', 'سندويش هاوي', 4000, true, true, 0, '[]'::jsonb),
  ('sandwich-chicken-sub', 'sandwiches', 'سندويش چكن ساب', 4000, true, true, 0, '[]'::jsonb),
  ('sandwich-jalapeno', 'sandwiches', 'سندويش تشيكن هالبينو', 4000, true, true, 0, '[]'::jsonb),
  ('meal-zinger', 'meals', 'وجبة زنجر', 5000, true, true, 0, '[]'::jsonb),
  ('meal-fajita', 'meals', 'وجبة فاهيتا دجاج', 5000, true, true, 0, '[]'::jsonb),
  ('meal-chicken-sub', 'meals', 'وجبة چكن ساب', 5000, true, true, 0, '[]'::jsonb),
  ('meal-filo', 'meals', 'وجبة فيلو', 5000, true, true, 0, '[]'::jsonb),
  ('meal-hawi', 'meals', 'وجبة هاوي', 5000, true, true, 0, '[]'::jsonb),
  ('meal-jalapeno', 'meals', 'وجبة تشيكن هالبينو', 5000, true, true, 0, '[]'::jsonb),
  ('shawarma-chicken-sandwich', 'shawarma', 'سندويش شاورما دجاج', 2500, true, true, 0, '[]'::jsonb),
  ('shawarma-meat-sandwich', 'shawarma', 'سندويش شاورما لحم', 3000, true, true, 0, '[]'::jsonb),
  ('saj-chicken', 'shawarma', 'صاج دجاج', 3000, true, true, 0, '[]'::jsonb),
  ('saj-meat', 'shawarma', 'صاج لحم', 4000, true, true, 0, '[]'::jsonb),
  ('arabic-chicken', 'shawarma', 'وجبة عربي دجاج', 5000, true, true, 0, '[]'::jsonb),
  ('arabic-meat', 'shawarma', 'وجبة عربي لحم', 6000, true, true, 0, '[]'::jsonb),
  ('jumbo-meat', 'shawarma', 'وجبة جامبو لحم', 10000, true, true, 0, '[]'::jsonb),
  ('jumbo-chicken', 'shawarma', 'وجبة جامبو دجاج', 9000, true, true, 0, '[]'::jsonb),
  ('funker-large', 'funker', 'فنكر كبير', 4000, true, true, 0, '[]'::jsonb),
  ('funker-medium', 'funker', 'فنكر وسط', 2500, true, true, 0, '[]'::jsonb),
  ('funker-small', 'funker', 'فنكر صغير', 1500, true, true, 0, '[]'::jsonb)
on conflict (id) do nothing;
