-- DARI Restaurant: schema, RLS, order RPC, realtime.
-- Run in Supabase Dashboard -> SQL Editor (or `supabase db push`).

create table if not exists public.categories (
  id text primary key,
  name_ar text not null,
  name_en text not null default '',
  is_visible boolean not null default true,
  sort_order int not null default 0
);

create table if not exists public.products (
  id text primary key,
  category_id text not null references public.categories (id) on update cascade,
  name_ar text not null,
  name_en text not null default '',
  description_ar text not null default '',
  description_en text not null default '',
  image text,
  price int not null check (price >= 0),
  is_available boolean not null default true,
  is_visible boolean not null default true,
  sort_order int not null default 0,
  -- [{"nameAr": "صغير", "price": 5000}, ...]
  variants jsonb not null default '[]'::jsonb
);

create table if not exists public.staff_profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  role text not null default 'cashier' check (role in ('cashier', 'admin')),
  is_active boolean not null default true
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity (start with 1001),
  source text not null check (source in ('TABLE_QR', 'PUBLIC_LINK', 'CASHIER_MANUAL')),
  order_type text not null check (order_type in ('DINE_IN', 'TAKEAWAY', 'DELIVERY')),
  status text not null default 'PENDING'
    check (status in ('PENDING', 'CONFIRMED', 'PREPARING', 'READY', 'COMPLETED', 'CANCELLED')),
  table_number int check (table_number is null or table_number > 0),
  customer_name text,
  customer_phone text,
  customer_address text,
  total int not null default 0 check (total >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_table_rules check (
    (order_type = 'DINE_IN') = (table_number is not null)
    or source = 'CASHIER_MANUAL'
  ),
  constraint orders_customer_rules check (
    source = 'CASHIER_MANUAL'
    or order_type = 'DINE_IN'
    or (
      coalesce(btrim(customer_name), '') <> ''
      and coalesce(btrim(customer_phone), '') <> ''
      and (order_type <> 'DELIVERY' or coalesce(btrim(customer_address), '') <> '')
    )
  )
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,
  product_id text not null,
  product_name text not null,
  variant text,
  unit_price int not null check (unit_price >= 0),
  quantity int not null check (quantity between 1 and 100),
  line_total int not null check (line_total >= 0)
);

create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (status);
create index if not exists order_items_order_id_idx on public.order_items (order_id);

-- Staff = a Supabase Auth user listed (and active) in staff_profiles.
create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.staff_profiles
    where user_id = auth.uid() and is_active
  );
$$;

-- Customers cannot insert into orders/order_items directly. They call this
-- function, which validates input and takes prices from the products table.
create or replace function public.create_order(
  p_source text,
  p_order_type text,
  p_table_number int,
  p_customer_name text,
  p_customer_phone text,
  p_customer_address text,
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_staff boolean := public.is_staff();
  v_order public.orders;
  v_item jsonb;
  v_product public.products;
  v_variant jsonb;
  v_variant_name text;
  v_qty int;
  v_price int;
  v_total int := 0;
  v_name text := nullif(btrim(coalesce(p_customer_name, '')), '');
  v_phone text := nullif(btrim(coalesce(p_customer_phone, '')), '');
  v_address text := nullif(btrim(coalesce(p_customer_address, '')), '');
begin
  if p_source not in ('TABLE_QR', 'PUBLIC_LINK', 'CASHIER_MANUAL') then
    raise exception 'invalid_source';
  end if;
  if p_source = 'CASHIER_MANUAL' and not v_staff then
    raise exception 'not_authorized';
  end if;
  if p_order_type not in ('DINE_IN', 'TAKEAWAY', 'DELIVERY') then
    raise exception 'invalid_order_type';
  end if;

  if p_source = 'TABLE_QR' then
    if p_order_type <> 'DINE_IN' or p_table_number is null or p_table_number < 1 then
      raise exception 'invalid_table';
    end if;
    v_name := null; v_phone := null; v_address := null;
  elsif p_source = 'PUBLIC_LINK' then
    if p_order_type not in ('TAKEAWAY', 'DELIVERY') then
      raise exception 'invalid_order_type';
    end if;
    if v_name is null or v_phone is null then
      raise exception 'customer_required';
    end if;
    if p_order_type = 'DELIVERY' and v_address is null then
      raise exception 'address_required';
    end if;
    if p_order_type = 'TAKEAWAY' then v_address := null; end if;
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array'
     or jsonb_array_length(p_items) = 0 or jsonb_array_length(p_items) > 100 then
    raise exception 'invalid_items';
  end if;

  insert into public.orders (
    source, order_type, table_number, customer_name, customer_phone, customer_address
  ) values (
    p_source, p_order_type,
    case when p_order_type = 'DINE_IN' then p_table_number end,
    v_name, v_phone, v_address
  ) returning * into v_order;

  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty := coalesce((v_item ->> 'quantity')::int, 0);
    if v_qty < 1 or v_qty > 100 then
      raise exception 'invalid_quantity';
    end if;

    select * into v_product from public.products where id = v_item ->> 'product_id';
    if not found or not v_product.is_available or not v_product.is_visible then
      raise exception 'product_unavailable:%', coalesce(v_item ->> 'product_id', '');
    end if;

    v_variant_name := nullif(v_item ->> 'variant', '');
    v_price := v_product.price;
    if v_variant_name is not null then
      select e into v_variant
      from jsonb_array_elements(v_product.variants) e
      where e ->> 'nameAr' = v_variant_name
      limit 1;
      if v_variant is null then
        raise exception 'invalid_variant:%', v_product.id;
      end if;
      v_price := (v_variant ->> 'price')::int;
    elsif jsonb_array_length(v_product.variants) > 0 then
      raise exception 'variant_required:%', v_product.id;
    end if;

    insert into public.order_items (
      order_id, product_id, product_name, variant, unit_price, quantity, line_total
    ) values (
      v_order.id, v_product.id, v_product.name_ar, v_variant_name,
      v_price, v_qty, v_price * v_qty
    );
    v_total := v_total + v_price * v_qty;
  end loop;

  update public.orders set total = v_total where id = v_order.id
  returning * into v_order;

  return jsonb_build_object(
    'id', v_order.id,
    'order_number', v_order.order_number,
    'total', v_order.total,
    'created_at', v_order.created_at
  );
end;
$$;

revoke all on function public.create_order(text, text, int, text, text, text, jsonb) from public;
grant execute on function public.create_order(text, text, int, text, text, text, jsonb)
  to anon, authenticated;
grant execute on function public.is_staff() to anon, authenticated;

-- Row Level Security
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.staff_profiles enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists categories_public_read on public.categories;
create policy categories_public_read on public.categories
  for select to anon, authenticated using (is_visible or public.is_staff());

drop policy if exists categories_staff_write on public.categories;
create policy categories_staff_write on public.categories
  for all to authenticated using (public.is_staff()) with check (public.is_staff());

drop policy if exists products_public_read on public.products;
create policy products_public_read on public.products
  for select to anon, authenticated using (is_visible or public.is_staff());

drop policy if exists products_staff_write on public.products;
create policy products_staff_write on public.products
  for all to authenticated using (public.is_staff()) with check (public.is_staff());

drop policy if exists staff_profiles_read_own on public.staff_profiles;
create policy staff_profiles_read_own on public.staff_profiles
  for select to authenticated using (user_id = auth.uid());

drop policy if exists orders_staff_read on public.orders;
create policy orders_staff_read on public.orders
  for select to authenticated using (public.is_staff());

drop policy if exists orders_staff_update on public.orders;
create policy orders_staff_update on public.orders
  for update to authenticated using (public.is_staff()) with check (public.is_staff());

drop policy if exists order_items_staff_read on public.order_items;
create policy order_items_staff_read on public.order_items
  for select to authenticated using (public.is_staff());

-- Table privileges: anon never touches orders directly; staff may only change status.
revoke all on public.orders, public.order_items, public.staff_profiles from anon;
revoke insert, delete, update on public.orders from authenticated;
revoke insert, update, delete on public.order_items from authenticated;
grant select on public.orders, public.order_items, public.staff_profiles to authenticated;
grant update (status, updated_at) on public.orders to authenticated;
grant select on public.categories, public.products to anon, authenticated;
grant insert, update, delete on public.categories, public.products to authenticated;

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists orders_touch_updated_at on public.orders;
create trigger orders_touch_updated_at
  before update on public.orders
  for each row execute function public.touch_updated_at();

-- Realtime: staff receive new/updated orders (RLS applies to realtime events).
do $$
begin
  alter publication supabase_realtime add table public.orders;
exception when duplicate_object then null;
end $$;
